# Generated by Django 3.0.7 on 2022-04-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='media/projects')),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
